name: CrediTrust Validation CI
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Verification
      run: |
        echo "Validating Folder Structure..."
        ls src/
        ls notebooks/
        python -c "print('Repository integrity check passed.')"
